version: "3.8"

services:
  tasks_app:
    build: .
    container_name: tasks_app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    links:
      - tasks_db
    depends_on:
      tasks_db:
        condition: service_healthy
    restart: always

  tasks_db:
    image: postgres
    container_name: tasks_db
    environment:
      - POSTGRES_DB=Tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5